### ISSUE TITLE
Missing: 'x708bat.py' & 'x708pld.py'

### ISSUE THREAD

**Issue by aarinmorris** [suptronics/x708#1]
After running the bash script (x708.sh), I get the following:

x708.sh: line 123: /home/pi/x708bat.py: No such file or directory
chmod: cannot access '/home/pi/x708bat.py': No such file or directory
x708.sh: line 151: /home/pi/x708pld.py: No such file or directory
chmod: cannot access '/home/pi/x708pld.py': No such file or directory

This is my third time installing this... The previous attempts worked perfectly. Not sure why this is happening. Can anyone help?

FYI. I'm running the latest version of Raspberry Pi OS Lite as well as OMV V5 on a Raspberry Pi 4 (8GB)

**Comment by aarinmorris** [comment]
Got it! Not much to explain... Just re-installed the OS with desktop environment rather than lite and it worked. I'm sure that I was just missing some dependency, I'm just not that versed in Linux yet.

**Comment by bf8392** [comment]
When this issue comes to you, then maybe your standard-user is not pi...than you have to manually create /home/pi to make the script run...I would suggest that the script creates his own folder where the scripts are kept instead of this, because of compatibility...also you can adjust the script with your prefered folder...
